/****** Object:  Table [dbo].[MED_ANESTHESIA_METHOD_TYPE]    Script Date: 10/15/2015 20:23:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MED_ANESTHESIA_METHOD_TYPE](
	[ANESTHESIA_METHOD] [varchar](20) NOT NULL,
	[INTRAVERTEBRAL_ANES_TYPE] [numeric](2, 0) NULL,
	[INTUBATE_ANES_TYPE] [varchar](20) NULL,
    [NON_INTUBATE_ANES_TYPE] [numeric](2, 0) NULL,
    [COMBINE_ANES_TYPE] [numeric](2, 0) NULL,
    [OTHER_ANES_TYPE] [numeric](2, 0) NULL,
    [ALL_ANESTHESIA] [numeric](2, 0) NULL,
    [EXTRA_CIRCULATION] [numeric](2, 0) NULL,
    [SPINAL_ANESTHESIA] [numeric](2, 0) NULL,
 CONSTRAINT [PK_MED_ANESTHESIA_METHOD_TYPE] PRIMARY KEY CLUSTERED 
(
	[ANESTHESIA_METHOD] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


