CREATE OR REPLACE PUBLIC SYNONYM MED_SELF_ASSESSMENT FOR MEDICU.MED_SELF_ASSESSMENT;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANESTHESIA_INPUT_DATA FOR MEDSURGERY.MED_ANESTHESIA_INPUT_DATA;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANESTHESIA_METHOD_TYPE FOR MEDSURGERY.MED_ANESTHESIA_METHOD_TYPE;
CREATE OR REPLACE PUBLIC SYNONYM V_MED_ANES_INFO FOR MEDSURGERY.V_MED_ANES_INFO;
CREATE OR REPLACE PUBLIC SYNONYM MED_HIS_USERS FOR MEDCOMM.MED_HIS_USERS;
CREATE OR REPLACE PUBLIC SYNONYM MED_DEPT_DICT FOR MEDCOMM.MED_DEPT_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPERATING_ROOM FOR MEDSURGERY.MED_OPERATING_ROOM;
