            -- CREATE TABLE
CREATE TABLE MEDSURGERY.MED_ANESTHESIA_INPUT_DATA
(
  PATIENT_ID           VARCHAR2(20) NOT NULL,
  VISIT_ID             NUMBER(2) NOT NULL,
  OPER_ID              NUMBER(2) NOT NULL,
  CANCELED_TYPE        VARCHAR2(20),
  PACU_TEMPERATURE     NUMBER(2),
  IN_ICU               NUMBER(2),
  TRACHEA_6H           NUMBER(2),
  TRACHEA_REMOVE       NUMBER(2),
  ANES_START_24H_DEATH NUMBER(2),
  ANES_START_24H_STOP  NUMBER(2),
  ANES_ANAPHYLAXIS     NUMBER(2),
  SPINAL_ANES_COMP     NUMBER(2),
  CENTRAL_VENOUS       NUMBER(2),
  SPINAL_ANES          NUMBER(2),
  TRACHEA_HOARSE       NUMBER(2),
  AFTER_ANES_COMA      NUMBER(2),
  GEN_ANES_TRACHEA     NUMBER(2),
  PACU_SITUATION       VARCHAR2(200),
  PACU_STEWARD         NUMBER(2),
  PACU_DOCTOR          VARCHAR2(8),
  PACU_NURSE           VARCHAR2(8),
  ANALGESIA_PUMP       VARCHAR2(20),
  ANALGESIA_METHOD     VARCHAR2(20),
  ANALGESIA_DRUGS      VARCHAR2(200),
  ANALGESIA_EFFECT     VARCHAR2(20),
  EXTRA_CIRCULATION    NUMBER(2),
  ANALGESIA_THERAPY    NUMBER(2),
  AFTER_ANALGESIA      NUMBER(2),
  MONARY_RES           NUMBER(2),
  MONARY_RES_OK        NUMBER(2),
  CONS_DISTURBANCE     NUMBER(2),
  OXYGEN_SATURATION    NUMBER(2),
  USE_REMINDERS        NUMBER(2),
  RES_TRACT_OBSTRUCE   NUMBER(2),
  ANES_DEATH           NUMBER(2),
  OTHER_NOT_EXP        NUMBER(2),
  DEATH_AFTER_OPER     NUMBER(2),
  NO_PLAN_IN_ICU       NUMBER(2),
  PAT_DIRECTION        VARCHAR2(20)
)
TABLESPACE TSP_MEDSURGERY
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 16M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.CANCELED_TYPE
  IS '取消类型；1-麻醉开始后手术开始前手术';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.PACU_TEMPERATURE
  IS '入PACU第一次测量体温低于35.5℃；1-是；0-否';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.IN_ICU
  IS '转入ICU患者；1-是；0-否';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.TRACHEA_6H
  IS '患者术后气管插管拔除后6小时内，非计划再次行气管插管；1-是；0-否';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.TRACHEA_REMOVE
  IS '术后气管插管拔除患者；1-是；0-否';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.ANES_START_24H_DEATH
  IS '麻醉开始后24小时内死亡（死亡原因）；1-是；0-否';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.ANES_START_24H_STOP
  IS '麻醉开始后24小时内心跳骤停患者（死亡原因）；1-是；0-否';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.ANES_ANAPHYLAXIS
  IS '麻醉期间严重过敏反应发生；1-是；0-否';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.SPINAL_ANES_COMP
  IS '椎管内麻醉后严重神经并发症发生；1-是；0-否';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.CENTRAL_VENOUS
  IS '中心静脉穿刺严重并发症发生；1-是；0-否';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.SPINAL_ANES
  IS '椎管内麻醉；1-是；0-否';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.TRACHEA_HOARSE
  IS '全麻气管插管拔管后声音嘶哑发生；1-是；0-否';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.AFTER_ANES_COMA
  IS '麻醉后新发昏迷发生；1-是；0-否';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.GEN_ANES_TRACHEA
  IS '全麻气管插管；1-是；0-否';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.PACU_SITUATION
  IS '入PACU情况';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.PACU_STEWARD
  IS '出PACU STEWARD 评分';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.PACU_DOCTOR
  IS 'PACU医师';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.PACU_NURSE
  IS 'PACU护士';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.ANALGESIA_PUMP
  IS '镇痛泵';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.ANALGESIA_METHOD
  IS '镇痛方式';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.ANALGESIA_DRUGS
  IS '镇痛药物';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.ANALGESIA_EFFECT
  IS '镇痛效果';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.EXTRA_CIRCULATION
  IS '体外循环；1-是；0-否';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.ANALGESIA_THERAPY
  IS '镇痛治疗；1-是；0-否';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.AFTER_ANALGESIA
  IS '术后镇痛；1-是；0-否';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.MONARY_RES
  IS '心肺复苏治疗；1-是；0-否';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.MONARY_RES_OK
  IS '心肺复苏治疗成功；1-是；0-否';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.CONS_DISTURBANCE
  IS '麻醉中发生未预期的意识障碍；1-是；0-否';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.OXYGEN_SATURATION
  IS '麻醉中出现氧饱和度重度降低；1-是；0-否';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.USE_REMINDERS
  IS '全身麻醉结束时使用催醒药物；1-是；0-否';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.RES_TRACT_OBSTRUCE
  IS '麻醉中因误咽误吸引发呼吸道梗阻；1-是；0-否';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.ANES_DEATH
  IS '麻醉意外死亡；1-是；0-否';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.OTHER_NOT_EXP
  IS '其他非预期的相关事件；1-是；0-否';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.DEATH_AFTER_OPER
  IS '术后死亡；1-是；0-否';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.NO_PLAN_IN_ICU
  IS '非计划转入ICU；1-是；0-否';
COMMENT ON COLUMN MEDSURGERY.MED_ANESTHESIA_INPUT_DATA.PAT_DIRECTION
  IS '病人去向；如转入病房';
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE MEDSURGERY.MED_ANESTHESIA_INPUT_DATA
  ADD CONSTRAINT PK_MED_ANESTHESIA_INPUT_DATA PRIMARY KEY (PATIENT_ID, VISIT_ID, OPER_ID)
  USING INDEX 
  TABLESPACE TSP_MEDSURGERY
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 2M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- GRANT/REVOKE OBJECT PRIVILEGES 
GRANT SELECT, INSERT, UPDATE, DELETE ON MEDSURGERY.MED_ANESTHESIA_INPUT_DATA TO ROLE_DOCARE;
