//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://115.236.176.100:57772/csp/multi/WebApp.WSGeneral.cls")]
        public string BLL_ZheDaZhongKongWebReference_WSGeneral {
            get {
                return ((string)(this["BLL_ZheDaZhongKongWebReference_WSGeneral"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.125:57772/csp/multi/BS.WS.OperWS.cls")]
        public string BLL_ZheDaZhongKongCopyBackWebReference_OperWS {
            get {
                return ((string)(this["BLL_ZheDaZhongKongCopyBackWebReference_OperWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.173/bitcinpbilltestwebservice/commservice.asmx")]
        public string BLL_WebReference_CommService {
            get {
                return ((string)(this["BLL_WebReference_CommService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.230/WebServiceTest/Service1.asmx")]
        public string BLL_DocareInterfaceTest_Service1 {
            get {
                return ((string)(this["BLL_DocareInterfaceTest_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.192.10.125/TrakCareECP/web//web.DHCICUSystemInterface.cls")]
        public string BLL_webHis_AnInterface {
            get {
                return ((string)(this["BLL_webHis_AnInterface"]));
            }
        }
    }
}
