CREATE OR REPLACE PUBLIC SYNONYM MED_PAT_MASTER_INDEX FOR SURGERY.PAT_MASTER_INDEX;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANESTHESIA_PLAN FOR SURGERY.ANESTHESIA_PLAN;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPERATION_NAME FOR SURGERY.OPERATION_NAME;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPERATION_SCHEDULE FOR SURGERY.OPERATION_SCHEDULE;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANAESTHESIA_DICT FOR SURGERY.ANAESTHESIA_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPERATION_MASTER FOR SURGERY.OPERATION_MASTER;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPERATION_CANCELED FOR SURGERY.OPERATION_CANCELED;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANESTHESIA_EVENT FOR SURGERY.ANESTHESIA_EVENT;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANESTHESIA_EVENT_OPEN FOR SURGERY.ANESTHESIA_EVENT_OPEN;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANESTHESIA_INPUT_DICT FOR SURGERY.ANESTHESIA_INPUT_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_DEPT_DICT FOR COMM.DEPT_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_USERS FOR COMM.USERS;
CREATE OR REPLACE VIEW COMM.MED_HIS_USERS
(USER_ID, USER_NAME, USER_DEPT, INPUT_CODE, USER_JOB, RESERVED01, CREATE_DATE)
AS(SELECT EMP_NO,NAME,DEPT_CODE,INPUT_CODE,JOB,1,'' FROM COMM.STAFF_DICT);
CREATE OR REPLACE PUBLIC SYNONYM MED_HIS_USERS FOR COMM.MED_HIS_USERS;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPERATING_ROOM
 FOR SURGERY.OPERATING_ROOM
;

