-- 将MED_OPERATION_MASTER_EXT表中的数据字段的类型由整型修改成小数型，因为这些数据在实际使用中是小数
-- Add/modify columns 
alter table MED_OPERATION_MASTER_EXT modify OUT_FLUIDS_AMOUNT NUMBER(8,4);
alter table MED_OPERATION_MASTER_EXT modify IN_FLUIDS_AMOUNT NUMBER(8,4);
alter table MED_OPERATION_MASTER_EXT modify INFUSION_TRAN_VOL NUMBER(8,4);
alter table MED_OPERATION_MASTER_EXT modify OUT_REMAINDER_AMOUNT NUMBER(8,4);
alter table MED_OPERATION_MASTER_EXT modify BLOOD_LOSSED NUMBER(8,4);
alter table MED_OPERATION_MASTER_EXT modify BLOOD_TRANSFUSED NUMBER(8,4);
alter table MED_OPERATION_MASTER_EXT modify URINE_AMOUNT NUMBER(8,4);
alter table MED_OPERATION_MASTER_EXT modify DRAINAGE_AMOUNT NUMBER(8,4);
alter table MED_OPERATION_MASTER_EXT modify WHOLE_BLOOD NUMBER(8,4);
alter table MED_OPERATION_MASTER_EXT modify PURE_RED_CELL NUMBER(8,4);
alter table MED_OPERATION_MASTER_EXT modify CRYSTALLOIDS NUMBER(8,4);
alter table MED_OPERATION_MASTER_EXT modify COLLOIDS NUMBER(8,4);
alter table MED_OPERATION_MASTER_EXT modify BLOOD_COAGULATION_FACTORS NUMBER(8,4);
alter table MED_OPERATION_MASTER_EXT modify ALBUMIN NUMBER(8,4);
alter table MED_OPERATION_MASTER_EXT modify PLASMA NUMBER(8,4);
alter table MED_OPERATION_MASTER_EXT modify PLASMA_SUBSTITUTE NUMBER(8,4);
alter table MED_OPERATION_MASTER_EXT modify EQUILIBRIUM_LIQUID NUMBER(8,4);
alter table MED_OPERATION_MASTER_EXT modify ORMAL_SALINE NUMBER(8,4);
alter table MED_OPERATION_MASTER_EXT modify VOLUVEN NUMBER(8,4);
alter table MED_OPERATION_MASTER_EXT modify GELOFUSINE NUMBER(8,4);
alter table MED_OPERATION_MASTER_EXT modify PLATELET NUMBER(8,4);
alter table MED_OPERATION_MASTER_EXT modify COOL_THING NUMBER(8,4);
alter table MED_OPERATION_MASTER_EXT modify CRY_WATHER NUMBER(8,4);
alter table MED_OPERATION_MASTER_EXT modify RED_BLOOD NUMBER(8,4);
alter table MED_OPERATION_MASTER_EXT modify OTHER_IN_AMOUNT NUMBER(8,4);
alter table MED_OPERATION_MASTER_EXT modify OTHER_OUT_AMOUNT NUMBER(8,4);
