--Modify MED_ANESTHESIA_INPUT_DATA£¬Add Column UNEXPECT_EVENT_REASON
alter table MED_ANESTHESIA_INPUT_DATA add (UNEXPECT_EVENT_REASON varchar2(200));

alter table MED_ANESTHESIA_INPUT_DATA add (PREVENT_STEP varchar2(200));

alter table MED_ANESTHESIA_INPUT_DATA add (BLOOD_EVENT NUMBER(2));
alter table MED_ANESTHESIA_INPUT_DATA add (OPER_EVENT NUMBER(2));
alter table MED_ANESTHESIA_INPUT_DATA add (ANES_EVENT NUMBER(2));
alter table MED_ANESTHESIA_INPUT_DATA add (PAT_INDETIFICATION NUMBER(2));
