--麻醉5.0表视图映射
-- Grant/Revoke synonym 
CREATE OR REPLACE PUBLIC SYNONYM MED_OPERATING_ROOM FOR MEDSURGERY.MED_OPERATING_ROOM;

--手术间字典表视图
CREATE OR REPLACE VIEW V_OPERATING_ROOM
AS SELECT A.*,A.DEPT_CODE OPER_DEPT_CODE FROM MED_OPERATING_ROOM A;

-- Grant/Revoke synonym 
CREATE OR REPLACE PUBLIC SYNONYM V_OPERATING_ROOM FOR V_OPERATING_ROOM;


--手术主表视图
CREATE OR REPLACE VIEW V_OPERATION_MASTER
AS SELECT A.*,A.EMERGENCY_INDICATOR EMERGENCY_IND,DECODE(A.ISOLATION_INDICATOR,2,2,1) AS ISOLATION_IND,
DECODE(A.ISOLATION_INDICATOR,3,2,1) AS RADIATE_IND,1 INFECTED_IND,A.OPERATION_CLASS OPER_CLASS
FROM MED_OPERATION_MASTER A;

-- Grant/Revoke synonym 
CREATE OR REPLACE PUBLIC SYNONYM V_OPERATION_MASTER FOR V_OPERATION_MASTER;

--手术预约表视图
CREATE OR REPLACE VIEW V_OPERATION_SCHEDULE
AS SELECT A.*,A.EMERGENCY_INDICATOR EMERGENCY_IND,DECODE(A.ISOLATION_INDICATOR,2,2,1) AS ISOLATION_IND,
DECODE(A.ISOLATION_INDICATOR,3,2,1) AS RADIATE_IND,1 INFECTED_IND,0  OPER_STATUS FROM MED_OPERATION_SCHEDULE A;

-- Grant/Revoke synonym 
CREATE OR REPLACE PUBLIC SYNONYM V_OPERATION_SCHEDULE FOR V_OPERATION_SCHEDULE;

--患者主表视图
CREATE OR REPLACE VIEW V_PAT_MASTER_INDEX
AS SELECT * FROM MED_PAT_MASTER_INDEX;

-- Grant/Revoke synonym 
CREATE OR REPLACE PUBLIC SYNONYM V_PAT_MASTER_INDEX FOR V_PAT_MASTER_INDEX;

--麻醉计划表视图
CREATE OR REPLACE VIEW V_ANESTHESIA_PLAN
AS SELECT * FROM MED_ANESTHESIA_PLAN;

-- Grant/Revoke synonym 
CREATE OR REPLACE PUBLIC SYNONYM V_ANESTHESIA_PLAN FOR V_ANESTHESIA_PLAN;

--手术名称表视图
CREATE OR REPLACE VIEW V_OPERATION_NAME
AS SELECT * FROM MED_OPERATION_NAME;

-- Grant/Revoke synonym 
CREATE OR REPLACE PUBLIC SYNONYM V_OPERATION_NAME FOR V_OPERATION_NAME;

--科室字典视图
CREATE OR REPLACE VIEW V_DEPT_DICT
AS SELECT * FROM MED_DEPT_DICT;

-- Grant/Revoke synonym 
CREATE OR REPLACE PUBLIC SYNONYM V_DEPT_DICT FOR V_DEPT_DICT;

--医护人员字典视图
CREATE OR REPLACE VIEW V_HIS_USERS
AS SELECT * FROM MED_HIS_USERS;

-- Grant/Revoke synonym 
CREATE OR REPLACE PUBLIC SYNONYM V_HIS_USERS FOR V_HIS_USERS;

--体征预警视图，若没有，新建；若有，但无法创建，新建同义词或赋权限
CREATE OR REPLACE VIEW V_ANES_ALARM_MESSAGE
AS SELECT * FROM MEDSURGERY.MED_ANES_ALARM_MESSAGE;

-- Grant/Revoke synonym 
CREATE OR REPLACE PUBLIC SYNONYM V_ANES_ALARM_MESSAGE FOR V_ANES_ALARM_MESSAGE;




