IF OBJECT_ID('V_OPER_ROOM_INFOS') IS NOT NULL
DROP VIEW V_OPER_ROOM_INFOS
GO
CREATE VIEW V_OPER_ROOM_INFOS AS
SELECT
TOP 100 percent
--手术间（复苏床位）名称
A.OPERATING_ROOM_NO BED_LABEL,
--手术间（复苏床位）号
A.OPERATING_ROOM_NO,
--台次
A.SEQUENCE,
--手术科室代码
A.OPERATING_ROOM OPER_DEPT_CODE,
--手术科室名称
ISNULL((SELECT V_DEPT_DICT.DEPT_NAME FROM V_DEPT_DICT WHERE V_DEPT_DICT.DEPT_CODE = A.OPERATING_DEPT),A.OPERATING_DEPT) OPER_DEPT_NAME,
--患者3个ID和住院号
A.PATIENT_ID,C.INP_NO,A.VISIT_ID,A.OPER_ID,
--手术日期
A.SCHEDULED_DATE_TIME,
--入手术室时间
A.IN_DATE_TIME,
--手术开始时间
A.START_DATE_TIME,
--患者姓名
C.NAME PAT_NAME,
--性别
C.SEX,
--年龄
DATEDIFF(YEAR,GETDATE(),C.DATE_OF_BIRTH) AS PAT_AGE,
--急诊择期标记
A.EMERGENCY_IND,
--隔离标记
A.ISOLATION_IND,
--放射标记
A.RADIATE_IND,
--感染标记
A.INFECTED_IND,
--住院科室名
ISNULL((SELECT V_DEPT_DICT.DEPT_NAME FROM V_DEPT_DICT WHERE V_DEPT_DICT.DEPT_CODE = A.DEPT_STAYED),A.DEPT_STAYED) DEPT_STAYED_NAME,
--手术名称
A.OPERATION_NAME,
--手术等级
A.OPERATION_SCALE,
--麻醉方法
A.ANESTHESIA_METHOD,
 --手术者
ISNULL( ( SELECT  V_HIS_USERS.USER_NAME FROM V_HIS_USERS WHERE V_HIS_USERS.USER_ID = A.SURGEON ),A.SURGEON ) SURGEON,
       --第一手术助手
       ISNULL( ( SELECT  V_HIS_USERS.USER_NAME FROM V_HIS_USERS WHERE V_HIS_USERS.USER_ID = A.FIRST_ASSISTANT ),A.FIRST_ASSISTANT ) FIRST_ASSISTANT,
       --麻醉医生
       ISNULL( ( SELECT  V_HIS_USERS.USER_NAME FROM V_HIS_USERS WHERE V_HIS_USERS.USER_ID = A.ANESTHESIA_DOCTOR ),A.ANESTHESIA_DOCTOR ) ANESTHESIA_DOCTOR,
       --副麻医生
       ISNULL( ( SELECT  V_HIS_USERS.USER_NAME FROM V_HIS_USERS WHERE V_HIS_USERS.USER_ID = A.ANESTHESIA_ASSISTANT ),A.ANESTHESIA_ASSISTANT ) ANESTHESIA_ASSISTANT,
       --第一洗手护士
       ISNULL( ( SELECT  V_HIS_USERS.USER_NAME FROM V_HIS_USERS WHERE V_HIS_USERS.USER_ID = A.FIRST_OPERATION_NURSE ),A.FIRST_OPERATION_NURSE ) FIRST_OPERATION_NURSE,
       --第一巡回护士
       ISNULL( ( SELECT  V_HIS_USERS.USER_NAME FROM V_HIS_USERS WHERE V_HIS_USERS.USER_ID = A.FIRST_SUPPLY_NURSE ),A.FIRST_SUPPLY_NURSE ) FIRST_SUPPLY_NURSE,
--手术状态代码
A.OPER_STATUS AS OPER_STATE_CODE,
--手术状态名
CASE A.OPER_STATUS WHEN 0 THEN '准备手术' WHEN 5 THEN '入手术室' WHEN 10 THEN '麻醉开始' WHEN 15 THEN '手术开始' WHEN 25 THEN '手术结束' WHEN 30 THEN '麻醉结束' WHEN 40 THEN '准备复苏' WHEN 45 THEN '入复苏室' WHEN 55 THEN '出复苏室' WHEN 60 THEN '回病房' WHEN 80 THEN '病案归档' WHEN -80 THEN '手术取消' END AS OPER_STATE,
--当前状态时间
CASE A.OPER_STATUS WHEN 5 THEN CONVERT(CHAR(5),A.IN_DATE_TIME,108) WHEN 10 THEN CONVERT(CHAR(5),A.ANES_START_TIME,108) WHEN 15 THEN CONVERT(CHAR(5),A.START_DATE_TIME,108) WHEN 25 THEN CONVERT(CHAR(5),A.END_DATE_TIME,108) WHEN 30 THEN CONVERT(CHAR(5),A.ANES_END_TIME,108) WHEN 45 THEN CONVERT(CHAR(5),A.IN_PACU_DATE_TIME,108) WHEN 55 THEN CONVERT(CHAR(5),A.OUT_PACU_DATE_TIME,108) WHEN 60 THEN ISNULL(CONVERT(CHAR(5),A.OUT_PACU_DATE_TIME,108),CONVERT(CHAR(5),A.OUT_DATE_TIME,108)) ELSE '' END AS PRO_TIME
FROM V_OPERATION_MASTER A 
LEFT OUTER JOIN V_PAT_MASTER_INDEX C ON A.PATIENT_ID = C.PATIENT_ID
WHERE convert(nvarchar(10),A.SCHEDULED_DATE_TIME,120) = convert(nvarchar(10),GETDATE(),120) AND A.OPER_STATUS <> -80
ORDER BY A.OPERATING_ROOM,A.OPERATING_ROOM_NO,A.IN_DATE_TIME;
