--SQL SERVER麻醉5.0表视图映射

--手术间字典表视图
IF OBJECT_ID('V_OPERATING_ROOM') IS NOT NULL
DROP VIEW V_OPERATING_ROOM
GO
CREATE VIEW V_OPERATING_ROOM AS
SELECT A.*,A.DEPT_CODE OPER_DEPT_CODE FROM MED_OPERATING_ROOM A ;

GO
--手术主表视图
IF OBJECT_ID('V_OPERATION_MASTER') IS NOT NULL
DROP VIEW V_OPERATION_MASTER
GO
CREATE  VIEW V_OPERATION_MASTER
AS SELECT A.*,A.EMERGENCY_INDICATOR EMERGENCY_IND,CASE A.ISOLATION_INDICATOR WHEN 2 THEN 2 ELSE 1 END AS ISOLATION_IND,
CASE A.ISOLATION_INDICATOR WHEN 3 THEN 2 ELSE 1 END AS RADIATE_IND,1 INFECTED_IND,A.OPERATION_CLASS OPER_CLASS
FROM MED_OPERATION_MASTER A ;

GO
--手术预约表视图
IF OBJECT_ID('V_OPERATION_SCHEDULE') IS NOT NULL
DROP VIEW V_OPERATION_SCHEDULE
GO
CREATE VIEW V_OPERATION_SCHEDULE
AS SELECT A.*,A.EMERGENCY_INDICATOR EMERGENCY_IND,CASE A.ISOLATION_INDICATOR WHEN 2 THEN 2 ELSE 1 END AS ISOLATION_IND,
CASE A.ISOLATION_INDICATOR WHEN 3 THEN 2 ELSE 1 END AS RADIATE_IND,1 INFECTED_IND,0  OPER_STATUS FROM MED_OPERATION_SCHEDULE A;

GO
--手术预约名称表视图
IF OBJECT_ID('V_SCHEDULED_OPERATION_NAME') IS NOT NULL
DROP VIEW V_SCHEDULED_OPERATION_NAME
GO
CREATE VIEW V_SCHEDULED_OPERATION_NAME
AS SELECT * FROM
MED_SCHEDULED_OPERATION_NAME;

GO
--患者主表视图
IF OBJECT_ID('V_PAT_MASTER_INDEX') IS NOT NULL
DROP VIEW V_PAT_MASTER_INDEX
GO
CREATE VIEW V_PAT_MASTER_INDEX
AS SELECT * FROM MED_PAT_MASTER_INDEX;

GO
--手术名称表视图
IF OBJECT_ID('V_OPERATION_NAME') IS NOT NULL
DROP VIEW V_OPERATION_NAME
GO
CREATE VIEW V_OPERATION_NAME
AS SELECT * FROM MED_OPERATION_NAME;

GO
--麻醉计划表视图
IF OBJECT_ID('V_ANESTHESIA_PLAN') IS NOT NULL
DROP VIEW V_ANESTHESIA_PLAN
GO
CREATE VIEW V_ANESTHESIA_PLAN
AS SELECT * FROM MED_ANESTHESIA_PLAN;

GO
--科室字典视图
IF OBJECT_ID('V_DEPT_DICT') IS NOT NULL
DROP VIEW V_DEPT_DICT
GO
CREATE  VIEW V_DEPT_DICT
AS SELECT * FROM MED_DEPT_DICT;

GO
--医护人员字典视图
IF OBJECT_ID('V_HIS_USERS') IS NOT NULL
DROP VIEW V_HIS_USERS
GO
CREATE VIEW V_HIS_USERS
AS SELECT * FROM MED_HIS_USERS;

GO
--体征预警视图，若没有，新建；若有，但无法创建，新建同义词或赋权限
IF OBJECT_ID('V_ANES_ALARM_MESSAGE') IS NOT NULL
DROP VIEW V_ANES_ALARM_MESSAGE
GO
CREATE VIEW V_ANES_ALARM_MESSAGE
AS SELECT * FROM MED_ANES_ALARM_MESSAGE;
