drop PUBLIC SYNONYM MED_PAT_MASTER_INDEX;
drop PUBLIC SYNONYM MED_ANESTHESIA_PLAN;
drop PUBLIC SYNONYM MED_OPERATION_NAME;
drop PUBLIC SYNONYM MED_OPERATION_SCHEDULE;
drop PUBLIC SYNONYM MED_ANAESTHESIA_DICT;
drop PUBLIC SYNONYM MED_OPERATION_MASTER;
drop PUBLIC SYNONYM MED_OPERATION_CANCELED;
drop PUBLIC SYNONYM MED_ANESTHESIA_EVENT;
drop PUBLIC SYNONYM MED_ANESTHESIA_EVENT_OPEN;
drop PUBLIC SYNONYM MED_ANESTHESIA_INPUT_DICT;
drop PUBLIC SYNONYM MED_DEPT_DICT;
drop PUBLIC SYNONYM MED_USERS;
drop PUBLIC SYNONYM MED_HIS_USERS;
drop PUBLIC SYNONYM MED_OPERATING_ROOM
;
drop PUBLIC SYNONYM MED_SELF_ASSESSMENT;
drop PUBLIC SYNONYM MED_ANESTHESIA_INPUT_DATA;
drop PUBLIC SYNONYM MED_ANESTHESIA_METHOD_TYPE;
drop PUBLIC SYNONYM V_MED_ANES_INFO;

drop TABLE SURGERY.MED_ANESTHESIA_INPUT_DATA;
drop TABLE SURGERY.MED_ANESTHESIA_METHOD_TYPE;
drop VIEW SURGERY.V_MED_ANES_INFO;
drop VIEW COMM.MED_HIS_USERS;

ALTER TABLE SURGERY.OPERATION_CANCELED DROP COLUMN OPER_ID;