DELETE FROM MED_PERMISSIONS MP
 WHERE MP.PERMISSION_ID IN
       (SELECT MPA.PERMISSION_ID
          FROM MED_PERMISSIONS_ANES MPA
         WHERE MPA.PARENT_ID = 'DoCare围术期管理决策平台');
COMMIT;

DELETE FROM MED_PERMISSIONS_ANES A WHERE A.PARENT_ID = 'DoCare围术期管理决策平台';
DELETE FROM med_permissions A WHERE A.PERMISSION_ID = 'DoCare围术期管理决策平台';
DELETE FROM med_roles A WHERE A.NAME = 'DoCare围术期管理决策平台';

COMMIT;

drop PUBLIC SYNONYM MED_SELF_ASSESSMENT;
drop PUBLIC SYNONYM MED_ANESTHESIA_INPUT_DATA;
drop PUBLIC SYNONYM MED_ANESTHESIA_METHOD_TYPE;
drop PUBLIC SYNONYM V_MED_ANES_INFO;

drop TABLE MEDSURGERY.MED_ANESTHESIA_INPUT_DATA;
drop TABLE MEDSURGERY.MED_ANESTHESIA_METHOD_TYPE;
drop VIEW MEDSURGERY.V_MED_ANES_INFO;

ALTER TABLE MEDSURGERY.MED_OPERATION_CANCELED  DROP COLUMN OPER_ID;
