drop TABLE MED_ANESTHESIA_INPUT_DATA;
drop TABLE MED_ANESTHESIA_METHOD_TYPE;
drop VIEW V_MED_ANES_INFO;

ALTER TABLE MED_OPERATION_CANCELED DROP COLUMN OPER_ID;

DELETE FROM MED_PERMISSIONS_ANES A WHERE A.PARENT_ID = 'DoCare围术期管理决策平台';
DELETE FROM med_permissions A WHERE A.PERMISSION_ID = 'DoCare围术期管理决策平台';
DELETE FROM med_roles A WHERE A.NAME = 'DoCare围术期管理决策平台';