//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalSystem.Anes.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MED_LAB_TEST_ITEMS
    {
        public string TEST_NO { get; set; }
        public int ITEM_NO { get; set; }
        public string ITEM_NAME { get; set; }
        public string ITEM_CODE { get; set; }
    }
}
