//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalSystem.Anes.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MED_EXAM_ITEMS
    {
        public string EXAM_NO { get; set; }
        public short EXAM_ITEM_NO { get; set; }
        public string EXAM_ITEM { get; set; }
        public string EXAM_ITEM_CODE { get; set; }
        public Nullable<decimal> COSTS { get; set; }
    }
}
