--///手术间字典表视图
CREATE VIEW V_OPERATING_ROOM
AS SELECT A.*,A.DEPT_CODE OPER_DEPT_CODE FROM MED_OPERATING_ROOM A;

--///手术主表视图
CREATE VIEW V_OPERATION_MASTER
AS SELECT A.*,
--手术室科室代码
A.OPER_ROOM OPERATING_ROOM,
--手术间号
A.OPER_ROOM_NO OPERATING_ROOM_NO,
--病人所在科室
A.DEPT_CODE DEPT_STAYED,
--手术状态
CASE A.OPER_STATUS_CODE WHEN 101 THEN -80 ELSE A.OPER_STATUS_CODE END AS OPER_STATUS,
--手术科室代码
A.OPER_DEPT_CODE AS OPERATING_DEPT,
--手术等级
A.OPER_SCALE AS OPERATION_SCALE,
--一些人员，手术助手，麻醉医生，麻醉助手，洗手和巡回护士等
A.FIRST_OPER_ASSISTANT AS FIRST_ASSISTANT,A.SECOND_OPER_ASSISTANT AS SECOND_ASSISTANT,A.THIRD_OPER_ASSISTANT AS THIRD_ASSISTANT,A.FOURTH_OPER_ASSISTANT AS FOURTH_ASSISTANT,
A.ANES_DOCTOR AS ANESTHESIA_DOCTOR,A.FIRST_ANES_ASSISTANT AS ANESTHESIA_ASSISTANT,A.SECOND_ANES_ASSISTANT AS SECOND_ANESTHESIA_ASSISTANT,A.THIRD_ANES_ASSISTANT AS THIRD_ANESTHESIA_ASSISTANT,A.FOURTH_ANES_ASSISTANT AS FOURTH_ANESTHESIA_ASSISTANT,
A.FIRST_OPER_NURSE AS FIRST_OPERATION_NURSE,A.SECOND_OPER_NURSE AS SECOND_OPERATION_NURSE,A.THIRD_OPER_NURSE AS THIRD_OPERATION_NURSE,
--麻醉方法
A.ANES_METHOD AS ANESTHESIA_METHOD ,
--手术体位
A.OPER_POSITION AS OPERATION_POSITION
FROM MED_OPERATION_MASTER A;

--///手术预约表视图
CREATE VIEW V_OPERATION_SCHEDULE
AS SELECT A.*,
--手术室科室代码
A.OPER_ROOM OPERATING_ROOM,
--手术间号
A.OPER_ROOM_NO OPERATING_ROOM_NO,
--病人所在科室
A.DEPT_CODE DEPT_STAYED,
--手术状态
0  OPER_STATUS,
A.OPER_STATUS_CODE AS STATE,
--手术科室代码
A.OPER_DEPT_CODE AS OPERATING_DEPT,
--手术等级
A.OPER_SCALE AS OPERATION_SCALE,
--一些人员，手术助手，麻醉医生，麻醉助手，洗手和巡回护士等
A.FIRST_OPER_ASSISTANT AS FIRST_ASSISTANT,A.SECOND_OPER_ASSISTANT AS SECOND_ASSISTANT,A.THIRD_OPER_ASSISTANT AS THIRD_ASSISTANT,A.FOURTH_OPER_ASSISTANT AS FOURTH_ASSISTANT,
A.ANES_DOCTOR AS ANESTHESIA_DOCTOR,A.FIRST_ANES_ASSISTANT AS ANESTHESIA_ASSISTANT,A.SECOND_ANES_ASSISTANT AS SECOND_ANESTHESIA_ASSISTANT,A.THIRD_ANES_ASSISTANT AS THIRD_ANESTHESIA_ASSISTANT,A.FOURTH_ANES_ASSISTANT AS FOURTH_ANESTHESIA_ASSISTANT,
A.FIRST_OPER_NURSE AS FIRST_OPERATION_NURSE,A.SECOND_OPER_NURSE AS SECOND_OPERATION_NURSE,A.THIRD_OPER_NURSE AS THIRD_OPERATION_NURSE,
--麻醉方法
A.ANES_METHOD AS ANESTHESIA_METHOD,
--手术体位
A.OPER_POSITION AS OPERATION_POSITION
FROM MED_OPERATION_SCHEDULE A;

--///患者主表视图
CREATE VIEW V_PAT_MASTER_INDEX
AS SELECT * FROM MED_PAT_MASTER_INDEX;

--///患者在院记录表视图
CREATE VIEW V_PATS_IN_HOSPITAL
AS SELECT * FROM MED_PATS_IN_HOSPITAL;

--手术名称表视图
CREATE VIEW V_OPERATION_NAME
AS SELECT A.*,A.OPER_SCALE AS OPERATION_SCALE FROM MED_OPERATION_NAME A;

--///麻醉计划表视图
CREATE VIEW V_ANESTHESIA_PLAN
AS SELECT * FROM MED_ANESTHESIA_PLAN;

--///科室字典视图
CREATE VIEW V_DEPT_DICT
AS SELECT * FROM MED_DEPT_DICT;

--///医护人员字典视图
CREATE VIEW V_HIS_USERS
AS SELECT U.*,U.USER_JOB_ID AS USER_ID FROM MED_HIS_USERS U;

--///体征预警视图
CREATE VIEW V_ANES_ALARM_MESSAGE
AS SELECT * FROM MEDSURGERY.MED_ANES_ALARM_MESSAGE;




